ANDROID:
  HOST: 192.168.0.34
  MESSAGE: Fire Detection
  PHONE_NUMBER: '+821083067118'
  PORT: 5000
PI:
  HOST: 192.168.1.11
  IR_PATH: /home/raspberry/pylepton/utils/static/ir_img.png
  PORT: 5000
  RGB_PATH: /home/raspberry/pylepton/utils/static/rgb_img.png
  SERIAL_PORT: /dev/spidev0.0
TWILIO:
  FROM_NUM: '+12513103845'
  SID: {SID}
  TOKEN: {TOKEN}
  TO_NUM: '+821074037133'
