ANDROID:
  PHONE_NUMBER: "+821074037133"
  MESSAGE: "Fire Detection"
PI:
  HOST: 192.168.1.2
  IR_PATH: /home/raspberry/pylepton/static/ir_img.png
  PORT: 5000
  RGB_PATH: /home/raspberry/pylepton/static/rgb_img.png
  SERIAL_PORT: '/dev/spidev0.0'
TWILIO:
  SID: '{SID}'
  TOKEN: '{TOKEN}'
  FROM_NUM: '+12513103845'
  TO_NUM: '+821074037133'
